# Generated by Django 3.2.5 on 2021-08-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataOfWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('humidity', models.FloatField(verbose_name='湿度')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('isRain', models.BooleanField(verbose_name='下雨状态')),
            ],
            options={
                'verbose_name': '门窗信息',
                'verbose_name_plural': '门窗信息',
                'db_table': 'data_of_winOrdoor',
            },
        ),
    ]
