# Generated by Django 3.2.5 on 2021-08-31 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_manufacture'),
        ('data', '0002_dataofwin_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('data', models.FloatField(verbose_name='数据')),
                ('type', models.CharField(max_length=30, verbose_name='数据类别')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '数据信息',
                'verbose_name_plural': '数据信息',
                'db_table': 'data',
            },
        ),
        migrations.DeleteModel(
            name='DataOfWin',
        ),
    ]
