# Generated by Django 3.2.5 on 2021-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210831_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('humidity', models.FloatField(verbose_name='湿度')),
                ('temperature', models.FloatField(verbose_name='温度')),
                ('distance', models.FloatField(verbose_name='距离')),
                ('foggy', models.SmallIntegerField(verbose_name='雾气')),
                ('rain', models.SmallIntegerField(verbose_name='下雨')),
                ('earthquake', models.SmallIntegerField(verbose_name='震动')),
                ('lightness', models.SmallIntegerField(verbose_name='亮度')),
            ],
            options={
                'verbose_name': '家庭数据展示',
                'verbose_name_plural': '家庭数据展示',
                'db_table': 'home',
            },
        ),
    ]
