# Generated by Django 3.2.5 on 2021-08-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=45, verbose_name='种类名称')),
            ],
            options={
                'verbose_name': '种类',
                'verbose_name_plural': '种类',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('name', models.CharField(max_length=45, verbose_name='姓名')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('place', models.CharField(max_length=30, verbose_name='产地')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.category', verbose_name='所属种类')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
                'db_table': 'device',
            },
        ),
    ]
