# Generated by Django 3.2.5 on 2021-08-30 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.family', verbose_name='所属家庭'),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.manufacturerinfo', verbose_name='所属制造商'),
        ),
    ]
