# Generated by Django 3.2.5 on 2021-08-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'user'), (1, 'manufacturer'), (2, 'admin')], default=2, verbose_name='类别'),
        ),
    ]
