# Generated by Django 3.2.5 on 2021-08-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
