# Generated by Django 3.2.5 on 2021-08-31 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='phone',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.family', verbose_name='所属家庭'),
        ),
    ]
