# Generated by Django 3.2.5 on 2021-08-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210831_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(default=0, verbose_name='电话'),
        ),
    ]
