# Generated by Django 3.2.5 on 2021-09-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userinfo_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='at_home',
            field=models.SmallIntegerField(default=1, verbose_name='是否在家'),
        ),
    ]
