# Generated by Django 3.2.5 on 2021-10-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_family_at_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=0, max_length=12, verbose_name='电话'),
        ),
    ]
